/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    KChart: typeof import('./../src/components/KChart.vue')['default']
    KLegends: typeof import('./../src/components/KLegends.vue')['default']
    KToolTip: typeof import('./../src/components/KToolTip.vue')['default']
    NSelect: typeof import('naive-ui')['NSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../src/components/Search.vue')['default']
  }
}
