export interface Index {
  assetsClassify: string;
  assetsClassifyEn: string;
  consNumber: string;
  currency: string;
  currencyEn: string;
  hotSpot: null | string;
  hotSpotEn: null | string;
  ifCustomized: string;
  ifCustomizedEn: string;
  ifProtect: null;
  ifTopDing: null;
  ifTracked: string;
  ifTrackedEn: string;
  ifWeightCapped: string;
  ifWeightCappedEn: string;
  indexClassify: string;
  indexClassifyEn: string;
  indexCode: string;
  indexCompliance: string;
  indexComplianceEn: string;
  indexName: string;
  indexNameEn: string;
  indexSeries: string;
  indexSeriesEn: string;
  indexType: null;
  key: string;
  latestClose: string;
  monthlyReturn: string;
  protectEndDate: null;
  protectStartDate: null;
  publishDate: string;
  region: string;
  regionEn: string;
}